version: '3'
services:
  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgres
    ports:
      - 4000:4000
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
