version: '3'
services:
  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 4000:4000
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todover

volumes:
  pgdata:
